package Tampilan;

import java.awt.Dimension;
import static java.awt.Frame.MAXIMIZED_HORIZ;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import koneksi.java.koneksi;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Lenovo
 */
public class Home extends javax.swing.JFrame {
    
    public static String userakses;
    private Connection conn = new koneksi().connect();
    java.util.Date tglsekarang = new java.util.Date();
    private SimpleDateFormat smpdtfmt = new SimpleDateFormat("dd MMMM yyyy", Locale.getDefault());
    //diatas adalah pengaturan format penulisan, bisa diubah sesuai keinginan.
    private String tanggal = smpdtfmt.format(tglsekarang);

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        Locale locale = new Locale ("id","ID");
        Locale.setDefault(locale);
        this.setLocationRelativeTo(null);
        lbl_tgl.setText(tanggal);
        setJam();
        //lblberanda2.setVisible(true);
        
        // jLabel1.setVisible(false);
    }
   
    public final void setJam() {
        ActionListener taskPerformer = new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent evt) {
                String nol_jam = "", nol_menit = "", nol_detik = "";

                java.util.Date dateTime = new java.util.Date();
                int nilai_jam = dateTime.getHours();
                int nilai_menit = dateTime.getMinutes();
                int nilai_detik = dateTime.getSeconds();

                if (nilai_jam <= 9) {
                    nol_jam = "0";
                }
                if (nilai_menit <= 9) {
                    nol_menit = "0";
                }
                if (nilai_detik <= 9) {
                    nol_detik = "0";
                }

                String jam = nol_jam + Integer.toString(nilai_jam);
                String menit = nol_menit + Integer.toString(nilai_menit);
                String detik = nol_detik + Integer.toString(nilai_detik);

                lbl_waktu.setText(jam + ":" + menit + ":" + detik + "");
            }
        };
        new Timer(1000, taskPerformer).start();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel2 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbl_waktu = new javax.swing.JLabel();
        lbl_tgl = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        biodata_siswa = new javax.swing.JMenuItem();
        data_nilai = new javax.swing.JMenuItem();
        absensi_siswa = new javax.swing.JMenuItem();
        tentukan_ranking = new javax.swing.JMenuItem();
        daftar_ranking = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        biodata_guru = new javax.swing.JMenuItem();
        jadwal_pelajaran = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        data_tabungan_siswa = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        daftar_admin = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        laporan_siswa = new javax.swing.JMenuItem();
        laporan_guru = new javax.swing.JMenuItem();
        laporan_absensi = new javax.swing.JMenuItem();
        laporan_nilai = new javax.swing.JMenuItem();
        laporan_jadwal_guru = new javax.swing.JMenuItem();
        laporan_datakeuangan = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        logout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jDesktopPane1.setBackground(new java.awt.Color(51, 51, 255));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel2.setText("WAKTU DAN TANGGAL ");
        jDesktopPane1.add(jLabel2);
        jLabel2.setBounds(1200, 600, 170, 17);

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/logo3.png"))); // NOI18N
        jDesktopPane1.add(jLabel18);
        jLabel18.setBounds(1130, 0, 150, 140);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/dinas pendidikan.png"))); // NOI18N
        jDesktopPane1.add(jLabel17);
        jLabel17.setBounds(940, 640, 230, 50);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/sql.png"))); // NOI18N
        jDesktopPane1.add(jLabel16);
        jLabel16.setBounds(810, 620, 140, 83);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/netbeans.png"))); // NOI18N
        jDesktopPane1.add(jLabel15);
        jLabel15.setBounds(660, 650, 190, 40);

        jLabel14.setFont(new java.awt.Font("Tekton Pro Ext", 1, 18)); // NOI18N
        jLabel14.setText("Powered By :");
        jDesktopPane1.add(jLabel14);
        jLabel14.setBounds(660, 610, 160, 20);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("_______________________________________________");
        jDesktopPane1.add(jLabel12);
        jLabel12.setBounds(50, 610, 340, 20);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Kecamatan Cengkareng, Kota Jakarta Barat, Daerah Khusus Ibukota Jakarta 11750");
        jDesktopPane1.add(jLabel11);
        jLabel11.setBounds(160, 680, 480, 17);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Alamat Sekolah   :  Jl. Raya Duri Kosambi No.19, RT.1/RW.1, Duri Kosambi");
        jDesktopPane1.add(jLabel10);
        jLabel10.setBounds(50, 660, 460, 17);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Contact Person  :   021-5415850");
        jDesktopPane1.add(jLabel9);
        jLabel9.setBounds(50, 637, 190, 20);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/jayaraya.png"))); // NOI18N
        jLabel7.setText("jLabel7");
        jDesktopPane1.add(jLabel7);
        jLabel7.setBounds(90, 10, 130, 144);

        lbl_waktu.setFont(new java.awt.Font("Rockwell", 3, 24)); // NOI18N
        lbl_waktu.setText("TIME");
        jDesktopPane1.add(lbl_waktu);
        lbl_waktu.setBounds(1210, 630, 110, 20);

        lbl_tgl.setFont(new java.awt.Font("Rockwell", 3, 14)); // NOI18N
        lbl_tgl.setText("Date");
        jDesktopPane1.add(lbl_tgl);
        lbl_tgl.setBounds(1220, 650, 140, 30);

        jLabel8.setFont(new java.awt.Font("Eras Light ITC", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Informasi Sekolah SMP N 176 Jakarta :");
        jDesktopPane1.add(jLabel8);
        jLabel8.setBounds(50, 600, 330, 30);

        jLabel1.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SISTEM INFORMASI ADMINISTRASI AKADEMIK SISWA");
        jDesktopPane1.add(jLabel1);
        jLabel1.setBounds(290, 20, 790, 50);

        jLabel4.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("SMPN 176 JAKARTA BARAT");
        jDesktopPane1.add(jLabel4);
        jLabel4.setBounds(470, 80, 400, 40);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/background home.jpg"))); // NOI18N
        jDesktopPane1.add(jLabel5);
        jLabel5.setBounds(-10, -60, 1440, 840);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/logo.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jDesktopPane1.add(jButton1);
        jButton1.setBounds(450, 160, 400, 310);

        jLabel3.setText("jLabel3");
        jDesktopPane1.add(jLabel3);
        jLabel3.setBounds(750, 620, 34, 14);

        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, 780));

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setForeground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuBar1.setMaximumSize(new java.awt.Dimension(1050, 32769));

        jMenu7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/tut wuri.png"))); // NOI18N
        jMenu7.setBorderPainted(true);
        jMenu7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenu7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenu7.setMaximumSize(new java.awt.Dimension(60, 32767));
        jMenu7.setOpaque(true);

        jMenuItem8.setText("VISI DAN MISI");
        jMenu7.add(jMenuItem8);

        jMenuBar1.add(jMenu7);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/siswa.png"))); // NOI18N
        jMenu2.setText("DATA SISWA ");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenu2.setMaximumSize(new java.awt.Dimension(200, 32767));
        jMenu2.setPreferredSize(new java.awt.Dimension(160, 41));

        biodata_siswa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        biodata_siswa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/biodata siswa.png"))); // NOI18N
        biodata_siswa.setText(" BIODATA  SISWA");
        biodata_siswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                biodata_siswaActionPerformed(evt);
            }
        });
        jMenu2.add(biodata_siswa);

        data_nilai.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        data_nilai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/data nilai.png"))); // NOI18N
        data_nilai.setText(" DATA NILAI");
        data_nilai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                data_nilaiActionPerformed(evt);
            }
        });
        jMenu2.add(data_nilai);

        absensi_siswa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        absensi_siswa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/absen siswa.png"))); // NOI18N
        absensi_siswa.setText(" ABSENSI SISWA");
        absensi_siswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                absensi_siswaActionPerformed(evt);
            }
        });
        jMenu2.add(absensi_siswa);

        tentukan_ranking.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tentukan_ranking.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/tentukan ranking.png"))); // NOI18N
        tentukan_ranking.setText(" TENTUKAN RANKING");
        tentukan_ranking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tentukan_rankingActionPerformed(evt);
            }
        });
        jMenu2.add(tentukan_ranking);

        daftar_ranking.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        daftar_ranking.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/daftar ranking.png"))); // NOI18N
        daftar_ranking.setText(" DAFTAR RANKING");
        daftar_ranking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daftar_rankingActionPerformed(evt);
            }
        });
        jMenu2.add(daftar_ranking);

        jMenuBar1.add(jMenu2);

        jMenu4.setBackground(new java.awt.Color(0, 255, 255));
        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/guru.png"))); // NOI18N
        jMenu4.setText("DATA GURU");
        jMenu4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenu4.setMaximumSize(new java.awt.Dimension(200, 327));

        biodata_guru.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        biodata_guru.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/biodata guru.png"))); // NOI18N
        biodata_guru.setText(" BIODATA GURU");
        biodata_guru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                biodata_guruActionPerformed(evt);
            }
        });
        jMenu4.add(biodata_guru);

        jadwal_pelajaran.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jadwal_pelajaran.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/jadwal pelajaran.png"))); // NOI18N
        jadwal_pelajaran.setText(" JADWAL PELAJARAN");
        jadwal_pelajaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jadwal_pelajaranActionPerformed(evt);
            }
        });
        jMenu4.add(jadwal_pelajaran);

        jMenuBar1.add(jMenu4);

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/keuangan.png"))); // NOI18N
        jMenu6.setText("DATA KEUANGAN");
        jMenu6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenu6.setMaximumSize(new java.awt.Dimension(220, 32767));

        data_tabungan_siswa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        data_tabungan_siswa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/tabungan.png"))); // NOI18N
        data_tabungan_siswa.setText("KEUANGAN SISWA");
        data_tabungan_siswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                data_tabungan_siswaActionPerformed(evt);
            }
        });
        jMenu6.add(data_tabungan_siswa);

        jMenuBar1.add(jMenu6);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/administrator.png"))); // NOI18N
        jMenu3.setText("DAFTAR ADMIN     ");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenu3.setMaximumSize(new java.awt.Dimension(220, 32767));

        daftar_admin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        daftar_admin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/admin sekolah.png"))); // NOI18N
        daftar_admin.setText(" DAFTAR ADMIN");
        daftar_admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daftar_adminActionPerformed(evt);
            }
        });
        jMenu3.add(daftar_admin);

        jMenuBar1.add(jMenu3);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/laporan.png"))); // NOI18N
        jMenu1.setText("LAPORAN");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenu1.setMaximumSize(new java.awt.Dimension(190, 32767));

        laporan_siswa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        laporan_siswa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/biodata siswa.png"))); // NOI18N
        laporan_siswa.setText("BIODATA SISWA");
        laporan_siswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporan_siswaActionPerformed(evt);
            }
        });
        jMenu1.add(laporan_siswa);

        laporan_guru.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        laporan_guru.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/biodata guru.png"))); // NOI18N
        laporan_guru.setText("BIODATA GURU");
        laporan_guru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporan_guruActionPerformed(evt);
            }
        });
        jMenu1.add(laporan_guru);

        laporan_absensi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        laporan_absensi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/absen siswa.png"))); // NOI18N
        laporan_absensi.setText("DATA ABSENSI SISWA");
        laporan_absensi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporan_absensiActionPerformed(evt);
            }
        });
        jMenu1.add(laporan_absensi);

        laporan_nilai.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        laporan_nilai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/data nilai.png"))); // NOI18N
        laporan_nilai.setText("DATA NILAI DAN RANKING SISWA ");
        laporan_nilai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporan_nilaiActionPerformed(evt);
            }
        });
        jMenu1.add(laporan_nilai);

        laporan_jadwal_guru.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        laporan_jadwal_guru.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/jadwal pelajaran.png"))); // NOI18N
        laporan_jadwal_guru.setText("DATA JADWAL PELAJARAN ");
        laporan_jadwal_guru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporan_jadwal_guruActionPerformed(evt);
            }
        });
        jMenu1.add(laporan_jadwal_guru);

        laporan_datakeuangan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        laporan_datakeuangan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/tabungan.png"))); // NOI18N
        laporan_datakeuangan.setText("DATA KEUANGAN SISWA");
        laporan_datakeuangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporan_datakeuanganActionPerformed(evt);
            }
        });
        jMenu1.add(laporan_datakeuangan);

        jMenuBar1.add(jMenu1);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/logout.png"))); // NOI18N
        jMenu5.setText("    LOGOUT    ");
        jMenu5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenu5.setMaximumSize(new java.awt.Dimension(150, 32767));
        jMenu5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenu5MousePressed(evt);
            }
        });

        logout.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/exit.png"))); // NOI18N
        logout.setText("LOGOUT");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        jMenu5.add(logout);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void biodata_siswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_biodata_siswaActionPerformed
        // TODO add your handling code here:
        datasiswa fm = new datasiswa();
        fm.setVisible(true);
    }//GEN-LAST:event_biodata_siswaActionPerformed

    private void jMenu5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu5MousePressed
        // TODO add your handling code here:
        // new login().setVisible(true);
        //dispose();
    }//GEN-LAST:event_jMenu5MousePressed

    private void data_nilaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_data_nilaiActionPerformed
        // TODO add your handling code here:
        datanilai fm = new datanilai();
        fm.setVisible(true);
    }//GEN-LAST:event_data_nilaiActionPerformed

    private void tentukan_rankingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tentukan_rankingActionPerformed
        // TODO add your handling code here:
        ranking fm = new ranking();
        fm.setVisible(true);
    }//GEN-LAST:event_tentukan_rankingActionPerformed

    private void daftar_adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daftar_adminActionPerformed
        // TODO add your handling code here:
        dataadmin fm = new dataadmin();
        fm.setVisible(true);
    }//GEN-LAST:event_daftar_adminActionPerformed

    private void daftar_rankingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daftar_rankingActionPerformed
        // TODO add your handling code here:
        tableranking fm = new tableranking();
        fm.setVisible(true);
    }//GEN-LAST:event_daftar_rankingActionPerformed

    private void buttonPeminjaman3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPeminjaman3ActionPerformed
        // TODO add your handling code here:
        datasiswa fm = new datasiswa();
        fm.setVisible(true);
    }//GEN-LAST:event_buttonPeminjaman3ActionPerformed

    private void buttonPeminjaman4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPeminjaman4ActionPerformed
        // TODO add your handling code here:
        datanilai fm = new datanilai();
        fm.setVisible(true);

    }//GEN-LAST:event_buttonPeminjaman4ActionPerformed

    private void buttonPeminjaman5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPeminjaman5ActionPerformed
        // TODO add your handling code here:
        ranking fm = new ranking();
        fm.setVisible(true);

    }//GEN-LAST:event_buttonPeminjaman5ActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        int jawab = JOptionPane.showOptionDialog(this,
                "Anda yakin ingin Logout?",
                "Logout",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE, null, null, null);

        if (jawab == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(this, "Berhasil Logout");
            new login().setVisible(true);
            this.setVisible(false);
            Home x = new Home();
                x.setVisible(false);
        }
    }//GEN-LAST:event_logoutActionPerformed

    private void laporan_nilaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporan_nilaiActionPerformed
        // TODO add your handling code here:
        Laporan.laporan_data_nilai_dan_ranking ns = new Laporan.laporan_data_nilai_dan_ranking();
        ns.setVisible(true);
    }//GEN-LAST:event_laporan_nilaiActionPerformed

    private void laporan_guruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporan_guruActionPerformed
        // TODO add your handling code here:
        Laporan.laporan_data_guru dg = new Laporan.laporan_data_guru();
        dg.setVisible(true);
    }//GEN-LAST:event_laporan_guruActionPerformed

    private void laporan_siswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporan_siswaActionPerformed
        // TODO add your handling code here:
        Laporan.laporan_data_siswa ds = new Laporan.laporan_data_siswa();
        ds.setVisible(true);
    }//GEN-LAST:event_laporan_siswaActionPerformed

    private void laporan_jadwal_guruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporan_jadwal_guruActionPerformed
        // TODO add your handling code here:
        Laporan.laporan_mata_pelajaran mp = new Laporan.laporan_mata_pelajaran();
        mp.setVisible(true);
    }//GEN-LAST:event_laporan_jadwal_guruActionPerformed

    private void absensi_siswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_absensi_siswaActionPerformed
        // TODO add your handling code here:
        absensi fm = new absensi();
        fm.setVisible(true);
    }//GEN-LAST:event_absensi_siswaActionPerformed

    private void data_tabungan_siswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_data_tabungan_siswaActionPerformed
        // TODO add your handling code here:
        bankkelas fm = new bankkelas();
        fm.setVisible(true);
    }//GEN-LAST:event_data_tabungan_siswaActionPerformed

    private void jadwal_pelajaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jadwal_pelajaranActionPerformed
        // TODO add your handling code here:
        datamatapelajaran fm = new datamatapelajaran();
        fm.setVisible(true);
    }//GEN-LAST:event_jadwal_pelajaranActionPerformed

    private void biodata_guruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_biodata_guruActionPerformed
        // TODO add your handling code here:
        dataguru fm = new dataguru();
        fm.setVisible(true);
    }//GEN-LAST:event_biodata_guruActionPerformed

    private void laporan_absensiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporan_absensiActionPerformed
        // TODO add your handling code here:
        Laporan.laporan_data_absensi  ab= new Laporan.laporan_data_absensi();
        ab.setVisible(true);
    }//GEN-LAST:event_laporan_absensiActionPerformed

    private void laporan_datakeuanganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporan_datakeuanganActionPerformed
        // TODO add your handling code here:
        Laporan.laporan_keuangan  ac= new Laporan.laporan_keuangan();
        ac.setVisible(true);
    }//GEN-LAST:event_laporan_datakeuanganActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem absensi_siswa;
    private javax.swing.JMenuItem biodata_guru;
    private javax.swing.JMenuItem biodata_siswa;
    private javax.swing.JMenuItem daftar_admin;
    private javax.swing.JMenuItem daftar_ranking;
    private javax.swing.JMenuItem data_nilai;
    private javax.swing.JMenuItem data_tabungan_siswa;
    private javax.swing.JButton jButton1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jadwal_pelajaran;
    private javax.swing.JMenuItem laporan_absensi;
    private javax.swing.JMenuItem laporan_datakeuangan;
    private javax.swing.JMenuItem laporan_guru;
    private javax.swing.JMenuItem laporan_jadwal_guru;
    private javax.swing.JMenuItem laporan_nilai;
    private javax.swing.JMenuItem laporan_siswa;
    private javax.swing.JLabel lbl_tgl;
    private javax.swing.JLabel lbl_waktu;
    private javax.swing.JMenuItem logout;
    private javax.swing.JMenuItem tentukan_ranking;
    // End of variables declaration//GEN-END:variables
}
